- name: Kuber cluster init
  command: kubeadm init --control-plane-endpoint={{ ansible_fqdn }} --pod-network-cidr={{ pod_network_cidr }}

- name: Create folder .kube
  file:
    dest: .kube
    state: directory

- name: Copy kubernetes config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    remote_src: yes

#- name: Download calico
#  command: curl -O -L {{ CNI }}

#- name: Calico install
#  become: false
#  command: sudo kubectl apply -f calico.yaml --insecure-skip-tls-verify=true


- name: Generate join comand 
  command: kubeadm token create --print-join-command
  register: token
  async: 120
  poll: 10

- name: Copy join command to local file 
  local_action: copy content="{{ token.stdout_lines[0] }}" dest="./token"
