- name: Kuber cluster init
  command: kubeadm init --control-plane-endpoint={{ ansible_fqdn }} --pod-network-cidr={{ pod_network_cidr }}

- name: Copy kubernetes config
  shell: mkdir -p $HOME/.kube && sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Calico install
  command: kubectl apply -f {{ CNI }}

- name: Generate join comand 
  command: kubeadm token create --print-join-command
  register: token
  async: 120
  poll: 10

- name: Copy join command to local file 
  local_action: copy content="{{ token.stdout_lines[0] }}" dest="./token"
