- name: Install kubernetes packages
  ansible.builtin.apt:
    pkg:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: 
    - kubeadm
    - kubelet
    - kubectl

